# Generated by Django 2.0.5 on 2018-08-16 19:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=256)),
                ('Last_Name', models.CharField(max_length=256)),
                ('Email_Address', models.CharField(max_length=256)),
                ('Mobile_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Intereset', models.CharField(max_length=1000)),
            ],
        ),
    ]
